### ISSUE TITLE
Questions about the shadow denoising method used

### ISSUE THREAD

**Issue by expenses** [diharaw/HybridRendering#3]
Hi, thanks for making the sample freely available! 

I haven't ran it yet, so sorry if this is a question that would be explained by doing so. I'm curious about what method you're using for shadow denoising here. It appears that you're doing some temporal reprojection stuff and then running it the output through an A Trous filter? Is there a reference that you used for this method? It seems familiar to the [AMD FidelityFX shadow denoiser](https://gpuopen.com/fidelityfx-denoiser/#shadow) which unfortunately is a bit un-documented as well.

Shadow denoising seems to be an aspect of ray-tracing that doesn't have many good implementation guides, so any recommendations would be appreciated! Thanks in advance!

**Comment by diharaw** [comment]
Hi,
Sorry about that. I’m currently writing an accompanying blogpost that explains all the techniques used in the demo. 
But yeah, the shadow denoiser is based on SVGF and uses a temporal accumulation pass that borrows a few tricks from the FidelityFX denoiser. The blogpost would go into further detail so I’ll link that here as soon as possible :D

**Comment by expenses** [comment]
Oh okay, fantastic! Looking forward to the blog post!

**Comment by TravisGesslein** [comment]
Since the article is now live (https://diharaw.github.io/post/adventures_in_hybrid_rendering/) thanks for that. 

This github issue isn't really the best place to ask, but since implementing this is probably still relatively fresh in your mind I would like to know your opinion on something:  

One thing that keeps coming up in literature is that people use variance (temporally or spatially) to adjust filtering for the level of noisyness in regions. But certain sources (e.g. http://casual-effects.com/research/Heitz2018Shadow/Heitz2018SIGGRAPHTalk.pdf , slide 52 onwards) point out that variance is not a particularly good measure for noise and suggest alternatives (total variation in this case). Have you considered trying out other measures (instead of variance) to measure the noise of pixels over time or regions of pixels?

**Comment by diharaw** [comment]
@TravisGesslein I haven't actually tried the other methods yet. I did skim over that paper yet but I wanted to have some working implementation as a starting point before I tried out anything more exotic. I'll definitely look into that though! 

@expenses The blog post is live as mentioned in the last comment. Please let me know if you've got any questions.

**Comment by expenses** [comment]
Hey, this blog post looks perfect! I'm also going to make a renderdoc capture to examine it closer, but I have a good idea of what to do now.
